#!/bin/bash

# Installing the 3x-ui panel for VLESS and 10‑year certificates

# Install OpenSSL
if ! command -v openssl &> /dev/null; then
  sudo apt update && sudo apt install -y openssl
  if [ $? -ne 0 ]; then
    exit 1
  fi
fi

# Install qrencode
if ! command -v qrencode &> /dev/null; then
  sudo apt update && sudo apt install -y qrencode
  if [ $? -ne 0 ]; then
    exit 1
  fi
fi

# Function that waits for the user to press Enter
wait_for_enter() {
  echo -e "Press Enter to continue..."
  read -r
}

# Install 3X-UI
if ! command -v x-ui &> /dev/null; then
  bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)
  if [ $? -ne 0 ]; then
    exit 1
  fi
else
  echo "3X-UI is already installed."
fi

# Start 3X-UI
systemctl daemon-reload
if systemctl list-units --full -all | grep -Fq 'x-ui.service'; then
  systemctl enable x-ui
  systemctl start x-ui
else
  x-ui
fi

# Function that waits for the user to press Enter
wait_for_enter() {
  echo -e "Press Enter to continue..."
  read -r
}

# Separator of 3 lines
for i in {1..3}; do echo "============================================================"; done

# Certificate generation
CERT_DIR="/etc/ssl/self_signed_cert"
CERT_NAME="self_signed"
DAYS_VALID=3650
mkdir -p "$CERT_DIR"
CERT_PATH="$CERT_DIR/$CERT_NAME.crt"
KEY_PATH="$CERT_DIR/$CERT_NAME.key"

openssl req -x509 -nodes -days $DAYS_VALID -newkey rsa:2048 \
  -keyout "$KEY_PATH" \
  -out "$CERT_PATH" \
  -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=example.com"

if [ $? -eq 0 ]; then
  echo "SSL CERTIFICATE PATH: $CERT_PATH"
  echo "SSL KEY PATH: $KEY_PATH"
else
  exit 1
fi

# Final message
echo "=============================================================="
echo "   Installation complete, keys generated!"
echo "   The only thing left is to put the key paths into the 3x-ui control panel"
echo "1) Go to the link above, enter the login and password generated by the script"
echo "2) After successful login go to the panel Settings"
echo "3) Paste the PUBLIC key certificate file path here: /etc/ssl/self_signed_cert/self_signed.crt"
echo "4) Paste the PRIVATE key certificate file path here: /etc/ssl/self_signed_cert/self_signed.key"
echo "5) Save and reload the panel"

echo "You are amazing!"
echo "=============================================================="